services:
  postgres:
    image: postgis/postgis:16-3.4 
    container_name: gavero_db
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: backend
    volumes:
      - pgdata:/var/lib/postgresql/data
      
volumes:
  pgdata: